# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeClawed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeClawed
  pod 'AlamofireImage', '4.0.0-beta.6'
  target 'DeClawedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeClawedUITests' do
    # Pods for testing
  end

end
